#spring.application.name=notepad
#logging.level.org.aphroache.coyotFze.http11=debug
spring:
  application:
    name: notepad

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/MemoryMate
    username: postgres
    password: 1234

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true